contact_links:
  - name: Telegram chat | Telegram чат
    url: https://t.me/remnawave_reverse
    about: Join our Telegram chat for community support and discussions | Присоединяйтесь к нашему чату в Telegram для поддержки сообщества и обсуждений